[package]
name = "rust-wad-examples"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies.lz-fear]
version = "0.1.1"

[dependencies.gltf]
version = "0.15"

[profile.release]
opt-level = "z"
lto = true
